"""
FedRAMP 20x machine-readable package renderer.

Reads the SAME capabilities the SSP renderer reads, emits FRMR-compatible
JSON. Structure follows the pattern established by Phase 1/2 public
submissions (Paramify, Knox, Confluent) and FedRAMP's machine-readable
schema. Adapter pattern — when FedRAMP renames `indicator` → `theme`
(as happened in v0.9.0-beta), only this file changes.

Run:  python -m renderers.fedramp_20x --out samples/20x_package.json
"""

from __future__ import annotations

import argparse
import hashlib
import json
from datetime import datetime, timezone
from pathlib import Path

from renderers.shared.capability_loader import (
    Capability,
    index_by_ksi,
    load_all,
)


def _digital_signature(payload: dict) -> str:
    canonical = json.dumps(payload, sort_keys=True, separators=(",", ":"))
    return hashlib.sha256(canonical.encode()).hexdigest()


def _ksi_short_name(ksi: str) -> str:
    """KSI-IAM-01 → IAM-01."""
    return ksi.replace("KSI-", "")


def _ksi_category_from_id(ksi: str) -> str:
    """KSI-IAM-01 → 'IAM' (and the friendly name is added downstream)."""
    return ksi.split("-")[1]


CATEGORY_NAMES = {
    "AFR": "Authorization by FedRAMP",
    "CED": "Cybersecurity Education",
    "CMT": "Change Management",
    "CNA": "Cloud Native Architecture",
    "IAM": "Identity and Access Management",
    "INR": "Incident Response",
    "MLA": "Monitoring, Logging, and Auditing",
    "PIY": "Policy and Inventory",
    "RPL": "Recovery Planning",
    "SVC": "Service Configuration",
    "TPR": "Third-Party Information Resources",
}


def render(
    csp_name: str = "Example CSP",
    cso_name: str = "Example Cloud Service Offering",
    impact: str = "Low",
) -> dict:
    caps = load_all()
    idx = index_by_ksi(caps)

    # Group KSIs by category
    by_category: dict[str, list[str]] = {}
    for ksi in idx:
        cat = _ksi_category_from_id(ksi)
        by_category.setdefault(cat, []).append(ksi)

    ksi_blocks = []
    for cat in sorted(by_category):
        validations = []
        for ksi in sorted(by_category[cat]):
            validations.append(_render_validation(ksi, idx[ksi]))
        ksi_blocks.append({
            "name": CATEGORY_NAMES.get(cat, cat),
            "shortName": cat,
            "validations": validations,
        })

    assessment = {
        "assessorOrg": "TBD",
        "date": datetime.now(timezone.utc).date().isoformat(),
        "leadAssessor": "TBD",
        "recommendation": "Pending",
        "remarks": "Generated by grc-toolkit; pending 3PAO review.",
        "ksis": ksi_blocks,
    }
    assessment["digitalSignature"] = _digital_signature(assessment)

    return {
        "package": {
            "cspName": csp_name,
            "cso": cso_name,
            "impact": impact,
            "frmrVersion": "v0.9.0-beta",
            "generatedAt": datetime.now(timezone.utc).isoformat(),
            "generator": "grc-toolkit",
            "assessments": [assessment],
        }
    }


def _render_validation(ksi: str, caps: list[Capability]) -> dict:
    """One KSI may be satisfied by N capabilities; merge them."""
    # Pull the per-cap coverage rows for this exact KSI
    coverage_rows = []
    for cap in caps:
        for entry in cap.ksis():
            if entry["ksi"] == ksi:
                coverage_rows.append((cap, entry))

    statements = [cap.statement for cap, _ in coverage_rows]

    coverage_levels = {entry["coverage"] for _, entry in coverage_rows}
    overall_coverage = (
        "full" if coverage_levels == {"full"}
        else "partial" if "partial" in coverage_levels or "contributes_to" in coverage_levels
        else "full"
    )

    # Evidence is union of all evidence across capabilities
    evidence_entries = []
    for cap, _ in coverage_rows:
        for ev in cap.evidence():
            evidence_entries.append({
                "id": ev["id"],
                "type": ev["type"],
                "source": ev["source"],
                "schedule": ev.get("schedule", "on-demand"),
                "validationOrigin": ev.get("validation_method", "automated"),
                "collector": ev.get("collector"),
                "validationRule": ev.get("validation_rule"),
                "fromCapability": cap.id,
            })

    return {
        "ksiId": ksi,
        "shortName": _ksi_short_name(ksi),
        "implementationStatus": "Implemented" if overall_coverage == "full" else "Partially Implemented",
        "coverage": overall_coverage,
        "implementation": "\n\n".join(statements),
        "contributingCapabilities": [cap.id for cap, _ in coverage_rows],
        "evidence": evidence_entries,
        "rationale": (
            None if overall_coverage == "full"
            else f"Coverage is {overall_coverage}; see contributing capabilities for scope notes."
        ),
    }


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", required=True, type=Path)
    ap.add_argument("--csp", default="Example CSP")
    ap.add_argument("--cso", default="Example Cloud Service Offering")
    ap.add_argument("--impact", default="Low")
    args = ap.parse_args()

    pkg = render(args.csp, args.cso, args.impact)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(json.dumps(pkg, indent=2))
    print(f"Wrote {args.out}")


if __name__ == "__main__":
    main()
