"""
FedRAMP 20x machine-readable package renderer.

Consumes the same capability index as the SSP renderer; emits FRMR-style
JSON. For aggregator-backed capabilities, each KSI block carries the
aggregator's live-state determination (status, statement, metrics,
timestamp) — not a hand-typed implementation claim.

Run:
    python -m renderers.fedramp_20x --out samples/20x_package.json
    python -m renderers.fedramp_20x --out samples/20x_package.json --fixtures tests/fixtures
"""

from __future__ import annotations

import argparse
import hashlib
import json
import uuid
from datetime import datetime, timezone
from pathlib import Path

from aggregators._base import AggregatorRunContext
from renderers.shared.capability_loader import (
    Capability,
    index_by_ksi,
    load_all,
)
from renderers.shared.determinations import DeterminationResolver, ResolvedCapabilityEntry


def _digital_signature(payload: dict) -> str:
    canonical = json.dumps(payload, sort_keys=True, separators=(",", ":"), default=str)
    return hashlib.sha256(canonical.encode()).hexdigest()


CATEGORY_NAMES = {
    "AFR": "Authorization by FedRAMP",
    "CED": "Cybersecurity Education",
    "CMT": "Change Management",
    "CNA": "Cloud Native Architecture",
    "IAM": "Identity and Access Management",
    "INR": "Incident Response",
    "MLA": "Monitoring, Logging, and Auditing",
    "PIY": "Policy and Inventory",
    "RPL": "Recovery Planning",
    "SVC": "Service Configuration",
    "TPR": "Third-Party Information Resources",
}


def _short_name(ksi: str) -> str:
    return ksi.replace("KSI-", "")


def _category(ksi: str) -> str:
    return ksi.split("-")[1]


def render(
    csp_name: str = "Example CSP",
    cso_name: str = "Example Cloud Service Offering",
    impact: str = "Low",
    fixtures_dir: str | None = None,
    strict_freshness: bool = False,
) -> dict:
    caps = load_all()
    idx = index_by_ksi(caps)

    ctx = AggregatorRunContext(
        fixture_mode=bool(fixtures_dir),
        fixture_dir=fixtures_dir or "",
        strict_freshness=strict_freshness,
        run_id=str(uuid.uuid4()),
    )
    resolver = DeterminationResolver(ctx)

    by_category: dict[str, list[str]] = {}
    for ksi in idx:
        by_category.setdefault(_category(ksi), []).append(ksi)

    ksi_blocks = []
    for cat in sorted(by_category):
        validations = []
        for ksi in sorted(by_category[cat]):
            entries = resolver.for_ksi(ksi, idx[ksi])
            validations.append(_render_validation(ksi, entries))
        ksi_blocks.append({
            "name": CATEGORY_NAMES.get(cat, cat),
            "shortName": cat,
            "validations": validations,
        })

    assessment = {
        "assessorOrg": "TBD",
        "date": datetime.now(timezone.utc).date().isoformat(),
        "leadAssessor": "TBD",
        "recommendation": "Pending",
        "remarks": "Generated by grc-toolkit; pending 3PAO review.",
        "ksis": ksi_blocks,
    }
    assessment["digitalSignature"] = _digital_signature(assessment)

    return {
        "package": {
            "cspName": csp_name,
            "cso": cso_name,
            "impact": impact,
            "frmrVersion": "v0.9.0-beta",
            "generatedAt": datetime.now(timezone.utc).isoformat(),
            "generator": "grc-toolkit",
            "runId": ctx.run_id,
            "assessments": [assessment],
        }
    }


def _render_validation(ksi: str, entries: list[ResolvedCapabilityEntry]) -> dict:
    aggregator_entries = [e for e in entries if e.determination]
    declared_entries = [e for e in entries if not e.determination]

    # Status rollup
    all_statuses = {e.determination.status for e in aggregator_entries}
    # For declared entries, fall back to per-control declared status if present
    for e in declared_entries:
        for ksi_entry in e.capability.ksis():
            if ksi_entry["ksi"] == ksi:
                # 20x KSI mappings don't carry implementation_status — use coverage
                cov = ksi_entry.get("coverage", "full")
                all_statuses.add(
                    "Implemented" if cov == "full" else "Partially Implemented"
                )
    if "Partially Implemented" in all_statuses:
        rollup_status = "Partially Implemented"
    elif "Planned" in all_statuses or "Inconclusive" in all_statuses:
        rollup_status = "Planned"
    elif all_statuses:
        rollup_status = "Implemented"
    else:
        rollup_status = "Not Documented"

    # Statements + evidence
    sources: list[dict] = []
    for e in aggregator_entries:
        d = e.determination
        sources.append({
            "capabilityId": e.capability.id,
            "source": "aggregator",
            "aggregator": e.capability.aggregator_path,
            "status": d.status,
            "observedAt": d.observed_at,
            "statement": d.statement,
            "metrics": d.metrics,
            "nonCompliant": d.non_compliant,
            "evidenceRefs": d.evidence_refs,
        })
    for e in declared_entries:
        sources.append({
            "capabilityId": e.capability.id,
            "source": "declared",
            "statement": e.declared_statement,
            "evidenceRefs": [ev["id"] for ev in e.capability.evidence()],
        })

    return {
        "ksiId": ksi,
        "shortName": _short_name(ksi),
        "implementationStatus": rollup_status,
        "contributingCapabilities": [e.capability.id for e in entries],
        "sources": sources,
    }


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", required=True, type=Path)
    ap.add_argument("--csp", default="Example CSP")
    ap.add_argument("--cso", default="Example Cloud Service Offering")
    ap.add_argument("--impact", default="Low")
    ap.add_argument("--fixtures", default=None)
    ap.add_argument("--strict-freshness", action="store_true")
    args = ap.parse_args()

    pkg = render(
        args.csp,
        args.cso,
        args.impact,
        fixtures_dir=args.fixtures,
        strict_freshness=args.strict_freshness,
    )
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(json.dumps(pkg, indent=2, default=str))
    print(f"Wrote {args.out}")


if __name__ == "__main__":
    main()
