"""
OSCAL System Security Plan (SSP) renderer — machine-readable Rev 5 output.

OSCAL is the format NIST and FedRAMP have publicly committed to for
machine-readable security documentation. As FedRAMP transitions to
mandating machine-readable Rev 5 packages (separate from the 20x FRMR
shape), OSCAL SSP is the most likely target format.

This renderer emits an OSCAL 1.2.0 SSP document. The control-implementation
section is populated from the same ControlDetermination objects the Word
and 20x renderers consume — author once, render to any FedRAMP path.

Scope: this is the SSP fragment that the toolkit can populate from
observed state. System characteristics (boundary, system info, FIPS-199
categorization, etc.) and inventory are emitted as placeholders that
the CSP fills in. The control-implementation block is the part this
toolkit owns.

Run:
    python -m renderers.oscal_ssp --out samples/oscal_ssp.json
    python -m renderers.oscal_ssp --out samples/oscal_ssp.json --fixtures tests/fixtures
"""

from __future__ import annotations

import argparse
import json
import uuid
from datetime import datetime, timezone
from pathlib import Path

from aggregators._base import AggregatorRunContext
from renderers.shared.capability_loader import (
    Capability,
    index_by_rev5_control,
    load_all,
)
from renderers.shared.determinations import DeterminationResolver, ResolvedCapabilityEntry


# FedRAMP-published OSCAL profile UUIDs. Source: github.com/GSA/fedramp-automation
# These are the canonical profiles a CSP imports into their SSP.
FEDRAMP_PROFILE_HREFS = {
    "Low":      "https://raw.githubusercontent.com/GSA/fedramp-automation/master/dist/content/rev5/baselines/json/FedRAMP_rev5_LOW-baseline_profile.json",
    "Moderate": "https://raw.githubusercontent.com/GSA/fedramp-automation/master/dist/content/rev5/baselines/json/FedRAMP_rev5_MODERATE-baseline_profile.json",
    "High":     "https://raw.githubusercontent.com/GSA/fedramp-automation/master/dist/content/rev5/baselines/json/FedRAMP_rev5_HIGH-baseline_profile.json",
}

OSCAL_VERSION = "1.2.0"


def _now() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


def _control_to_oscal_id(control_id: str) -> str:
    """OSCAL uses lowercase IDs with no parentheses: IA-2(1) → ia-2.1"""
    return control_id.lower().replace("(", ".").replace(")", "")


def render(
    csp_name: str = "Example CSP",
    cso_name: str = "Example Cloud Service Offering",
    impact: str = "Low",
    fixtures_dir: str | None = None,
    strict_freshness: bool = False,
) -> dict:
    caps = load_all()
    idx = index_by_rev5_control(caps)

    ctx = AggregatorRunContext(
        fixture_mode=bool(fixtures_dir),
        fixture_dir=fixtures_dir or "",
        strict_freshness=strict_freshness,
        run_id=str(uuid.uuid4()),
    )
    resolver = DeterminationResolver(ctx)

    ssp_uuid = str(uuid.uuid4())
    system_uuid = str(uuid.uuid4())
    this_party_uuid = str(uuid.uuid4())
    this_component_uuid = str(uuid.uuid4())

    implemented_requirements = []
    for control_id in sorted(idx.keys()):
        entries = resolver.for_rev5_control(control_id, idx[control_id])
        implemented_requirements.append(
            _build_implemented_requirement(
                control_id, entries, this_component_uuid
            )
        )

    return {
        "system-security-plan": {
            "uuid": ssp_uuid,
            "metadata": _build_metadata(ssp_uuid, csp_name, this_party_uuid),
            "import-profile": {
                "href": FEDRAMP_PROFILE_HREFS.get(impact, FEDRAMP_PROFILE_HREFS["Low"]),
            },
            "system-characteristics": _build_system_characteristics(
                system_uuid, cso_name, csp_name, impact, this_party_uuid
            ),
            "system-implementation": _build_system_implementation(
                this_party_uuid, this_component_uuid, csp_name
            ),
            "control-implementation": {
                "description": (
                    "Control implementations populated by grc-toolkit from "
                    "deterministic aggregators that observe live cloud / SaaS "
                    "state. Each implemented-requirement's by-component "
                    "statements include an observed-at timestamp and a "
                    "machine-determined implementation-status."
                ),
                "implemented-requirements": implemented_requirements,
            },
        }
    }


def _build_metadata(ssp_uuid: str, csp_name: str, party_uuid: str) -> dict:
    return {
        "title": f"System Security Plan — generated by grc-toolkit",
        "last-modified": _now(),
        "version": "0.1.0",
        "oscal-version": OSCAL_VERSION,
        "roles": [
            {
                "id": "system-owner",
                "title": "System Owner",
            },
        ],
        "parties": [
            {
                "uuid": party_uuid,
                "type": "organization",
                "name": csp_name,
            },
        ],
        "responsible-parties": [
            {
                "role-id": "system-owner",
                "party-uuids": [party_uuid],
            },
        ],
    }


def _build_system_characteristics(
    system_uuid: str,
    cso_name: str,
    csp_name: str,
    impact: str,
    party_uuid: str,
) -> dict:
    return {
        "system-ids": [
            {
                "identifier-type": "https://fedramp.gov",
                "id": f"placeholder-{system_uuid[:8]}",
            },
        ],
        "system-name": cso_name,
        "description": (
            f"PLACEHOLDER — replace with a system description authored by "
            f"the CSP ({csp_name}). This field is not derivable from cloud "
            "state."
        ),
        "security-sensitivity-level": impact.lower(),
        "system-information": {
            "information-types": [
                {
                    "uuid": str(uuid.uuid4()),
                    "title": "PLACEHOLDER information type",
                    "description": (
                        "PLACEHOLDER — the CSP categorizes their information "
                        "types per NIST SP 800-60. Confidentiality, integrity, "
                        "availability impact selections live here."
                    ),
                    "categorizations": [],
                    "confidentiality-impact": {"base": f"fips-199-{impact.lower()}"},
                    "integrity-impact":       {"base": f"fips-199-{impact.lower()}"},
                    "availability-impact":    {"base": f"fips-199-{impact.lower()}"},
                },
            ],
        },
        "security-impact-level": {
            "security-objective-confidentiality": impact.lower(),
            "security-objective-integrity":       impact.lower(),
            "security-objective-availability":    impact.lower(),
        },
        "status": {"state": "other", "remarks": "Draft generated by grc-toolkit"},
        "authorization-boundary": {
            "description": (
                "PLACEHOLDER — the CSP describes the authorization boundary "
                "here (logical and physical scope of the CSO). Not "
                "derivable from cloud state."
            ),
        },
        "responsible-parties": [
            {"role-id": "system-owner", "party-uuids": [party_uuid]},
        ],
    }


def _build_system_implementation(
    party_uuid: str,
    component_uuid: str,
    csp_name: str,
) -> dict:
    return {
        "users": [
            {
                "uuid": str(uuid.uuid4()),
                "title": "PLACEHOLDER user role",
                "role-ids": ["system-owner"],
            },
        ],
        "components": [
            {
                "uuid": component_uuid,
                "type": "this-system",
                "title": csp_name,
                "description": (
                    "The Cloud Service Offering as a whole. Sub-components "
                    "(databases, identity provider, etc.) added by the CSP."
                ),
                "status": {"state": "operational"},
                "responsible-roles": [
                    {"role-id": "system-owner", "party-uuids": [party_uuid]},
                ],
            },
        ],
    }


def _build_implemented_requirement(
    control_id: str,
    entries: list[ResolvedCapabilityEntry],
    component_uuid: str,
) -> dict:
    oscal_control_id = _control_to_oscal_id(control_id)
    rolled_up_status = _rollup_status(entries)

    by_components = []
    for entry in entries:
        if entry.determination:
            statement = entry.determination.statement
            observed_at = entry.determination.observed_at
            cap_source = f"{entry.capability.id} via {entry.capability.aggregator_path}"
        else:
            statement = entry.declared_statement
            observed_at = entry.capability.provenance().get("last_reviewed", "")
            cap_source = entry.capability.id

        by_components.append({
            "uuid": str(uuid.uuid4()),
            "component-uuid": component_uuid,
            "description": statement,
            "implementation-status": {
                "state": _oscal_status(
                    entry.determination.status if entry.determination
                    else _entry_declared_status(entry, control_id)
                ),
            },
            "props": [
                {"name": "capability-source", "value": cap_source},
                {"name": "observed-at",       "value": observed_at},
                {"name": "render-mode",       "value": "aggregator" if entry.determination else "declared"},
            ],
        })

    return {
        "uuid": str(uuid.uuid4()),
        "control-id": oscal_control_id,
        "by-components": by_components,
        "props": [
            {"name": "rolled-up-status", "value": rolled_up_status},
        ],
    }


def _rollup_status(entries: list[ResolvedCapabilityEntry]) -> str:
    statuses: set[str] = set()
    for e in entries:
        if e.determination:
            statuses.add(e.determination.status)
        else:
            for ctrl_entry in e.capability.rev5_controls():
                s = ctrl_entry.get("implementation_status")
                if s:
                    statuses.add(s)
    if "Planned" in statuses:
        return "planned"
    if "Partially Implemented" in statuses:
        return "partial"
    if "Inconclusive" in statuses:
        return "inconclusive"
    if "Alternative Implementation" in statuses:
        return "alternative"
    return "implemented" if statuses else "not-documented"


def _entry_declared_status(entry: ResolvedCapabilityEntry, control_id: str) -> str:
    for ctrl_entry in entry.capability.rev5_controls():
        if ctrl_entry["control"] == control_id:
            return ctrl_entry.get("implementation_status", "Implemented")
    return "Implemented"


def _oscal_status(status: str) -> str:
    """Map our status enum to OSCAL implementation-status state values."""
    mapping = {
        "Implemented": "implemented",
        "Partially Implemented": "partial",
        "Planned": "planned",
        "Alternative Implementation": "alternative",
        "Not Applicable": "not-applicable",
        "Inconclusive": "planned",  # OSCAL has no inconclusive; planned is closest
    }
    return mapping.get(status, "planned")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", required=True, type=Path)
    ap.add_argument("--csp", default="Example CSP")
    ap.add_argument("--cso", default="Example Cloud Service Offering")
    ap.add_argument("--impact", default="Low", choices=["Low", "Moderate", "High"])
    ap.add_argument("--fixtures", default=None)
    ap.add_argument("--strict-freshness", action="store_true")
    args = ap.parse_args()

    pkg = render(
        args.csp, args.cso, args.impact,
        fixtures_dir=args.fixtures,
        strict_freshness=args.strict_freshness,
    )
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(json.dumps(pkg, indent=2, default=str))
    print(f"Wrote {args.out}")


if __name__ == "__main__":
    main()
